#pragma once

#define NUMBER_OF_TRACKS 77
#define BYTES_PER_SECTOR 270
#define SECTORS_PER_TRACK 16
#define DISK_SIZE_BYTES (NUMBER_OF_TRACKS * BYTES_PER_SECTOR * SECTORS_PER_TRACK)

#define ACTIVE_FOR_TICKS 1600
